#!/usr/bin/env php
<?php
require_once 'Zend/Loader.php';
spl_autoload_register(array('Zend_Loader', 'autoload'));

$args = $argv;
array_shift($args);
try
{
    new USVN_Client_Client($args);
}
catch (Exception $e)
{
	USVN_Client_ConsoleUtils::writeOnStdError($e->getMessage()."\n");
    exit(1);
}
