#!/usr/bin/env php
<?php
require_once 'USVN/Client/Client.php';
require_once('USVN/Client/ConsoleUtils.php');

$args = $argv;
array_shift($args);
try
{
    new USVN_Client_Client($args);
}
catch (Exception $e)
{
	USVN_Client_ConsoleUtils::writeOnStdError($e->getMessage()."\n");
    exit(1);
}