<?php @unlink("../../SQL/data.sql"); ?>
<?php @unlink("../../Zend/Feed/EntryAbstract.php"); ?>
<?php @unlink("../../Zend/Feed/EntryAtom.php"); ?>
<?php @unlink("../../Zend/Feed/EntryRss.php"); ?>
<?php @unlink("../../Zend/Gdata/AuthException.php"); ?>
<?php @unlink("../../Zend/Gdata/BadMethodCallException.php"); ?>
<?php @unlink("../../Zend/Gdata/Base.php"); ?>
<?php @unlink("../../Zend/Gdata/Blogger.php"); ?>
<?php @unlink("../../Zend/Gdata/CodeSearch.php"); ?>
<?php @unlink("../../Zend/Gdata/Data.php"); ?>
<?php @unlink("../../Zend/Gdata/Exception.php"); ?>
<?php @unlink("../../Zend/Gdata/HttpException.php"); ?>
<?php @unlink("../../Zend/Gdata/InvalidArgumentException.php"); ?>
<?php @unlink("../../views/adminadmin/index.html"); ?>
<?php @unlink("../../views/browser/index.html"); ?>
<?php @unlink("../../views/configadmin/index.html"); ?>
<?php @unlink("../../views/groupadmin/edit.html"); ?>
<?php @unlink("../../views/groupadmin/exception.html"); ?>
<?php @unlink("../../views/groupadmin/form.html"); ?>
<?php @unlink("../../views/groupadmin/index.html"); ?>
<?php @unlink("../../views/groupadmin/new.html"); ?>
<?php @unlink("../../views/index/index.html"); ?>
<?php @unlink("../../views/login/errors.html"); ?>
<?php @unlink("../../views/login/login.html"); ?>
<?php @unlink("../../views/profile/index.html"); ?>
<?php @unlink("../../views/project/index.html"); ?>
<?php @unlink("../../views/project/managegroup.html"); ?>
<?php @unlink("../../views/projectadmin/edit.html"); ?>
<?php @unlink("../../views/projectadmin/exception.html"); ?>
<?php @unlink("../../views/projectadmin/form.html"); ?>
<?php @unlink("../../views/projectadmin/index.html"); ?>
<?php @unlink("../../views/projectadmin/new.html"); ?>
<?php @unlink("../../views/useradmin/edit.html"); ?>
<?php @unlink("../../views/useradmin/exception.html"); ?>
<?php @unlink("../../views/useradmin/form.html"); ?>
<?php @unlink("../../views/useradmin/import.html"); ?>
<?php @unlink("../../views/useradmin/index.html"); ?>
<?php @unlink("../../views/useradmin/new.html"); ?>
<?php @unlink("../../views/useradmin/profile.html"); ?>
