<div class="usvn_info">
	<h1><?= T_("Homepage") ?></h1>
</div>
<div id="usvn_index_projects" class="usvn_index_box">
	<h3><?= T_("Your projects") ?> <?= ($this->prefix != null ? '('.$this->prefix.')' : '') ?> :</h3>
  <? if (count($this->projects) || $this->prefix != null): ?>
    <ul class="grid_list">
    <?php if ($this->prefix != null): ?>
      <li>
      <a href="<?= $this->url(array('folder' => $this->prev), 'index'); ?>">
        <div class="grid_img">
          <?= $this->img('folder48.png') ?>
        </div>
        <div>..</div>
      </a>
      </li>
	  <?php endif ?>
	<? foreach ($this->projects as $project => $datas): ?>
		<li>
      <?php if ($datas->folder): ?>
			  <a href="<?= $this->url(array('folder' => $this->prefix.$project), 'index'); ?>">
  				<div class="grid_img">
  					<?= $this->img('folder48.png') ?>
  				</div>
			<?php else: ?>
			  <a href="<?= $this->url(array('project' => $this->prefix.$project), 'project'); ?>">
			    <div class="grid_img">
				    <?= $this->img('box48.png') ?>
			    </div>
      <?php endif ?>
				<div><?php
					if (strlen($project) > $this->maxlen) {
						echo substr($project, 0, $this->maxlen), '<br />';
						if (strlen($project) > ($this->maxlen * 2 - 3)) {
							echo substr($project, $this->maxlen, $this->maxlen - 3), '...';
						} else {
							echo substr($project, $this->maxlen);
						}
					} else {
				 		echo $project;
					}
				?></div>
			</a>
		</li>
	<? endforeach ?>
	</ul>
<? else: ?>
	<p><?= T_("You don't have any project.") ?></p>
<? endif ?>
</div>
<div id="usvn_index_groups" class="usvn_index_box">
	<h3><?= T_("Your groups"); ?>:</h3>
<? if (count($this->groups) || $this->prefix != null): ?>
	<ul class="grid_list">
	  <?php if ($this->prefix != null): ?>
      <li>
      <a href="<?= $this->url(array('folder' => $this->prev), 'index'); ?>">
        <div class="grid_img">
          <?= $this->img('folder48.png') ?>
        </div>
        <div>..</div>
      </a>
      </li>
	  <?php endif ?>
	<? foreach ($this->groups as $group => $datas): ?>
		<li>
	    <?php if ($datas instanceof USVN_Db_Table_Row_Project): ?>
			  <a href="<?= $this->url(array('folder' => $this->prefix), 'index'); ?>">
  				<div class="grid_img">
  					<?= $this->img('folder48.png') ?>
  				</div>
			<?php else: ?>
			  <a href="<?= $this->url(array('group' => $group), 'group'); ?>">
			    <div class="grid_img">
				    <?= $this->img('group48.png') ?>
			    </div>
      <?php endif ?>
				<div><?php
				 	if (strlen($group) > $this->maxlen) {
						echo substr($group, 0, $this->maxlen), '<br />';
						if (strlen($group) > ($this->maxlen * 2 - 3)) {
							echo substr($group, $this->maxlen, $this->maxlen - 3), '...';
						} else {
							echo substr($group, $this->maxlen);
						}
					} else {
				 		echo $group;
					}
				?></div>
			</a>
		</li>
	<? endforeach ?>
	</ul>
<? else: ?>
	<p><?= T_("You are not assigned to a group.") ?></p>
<? endif ?>
</div>
<div style="clear: both;">
	<img width="1" height="1" src="<?php echo $this->url(array('controller' => 'checkupdate')); ?>" />
</div>
