<div class="usvn_info">
	<h1><?= T_('Edit ticket') ?></h1>
</div>
<div id="profile">
	<form action="" method="POST" class="usvn_form">

		<label for="ticket[title]"><?= T_('Title') ?></label><br />
    <? if (!empty($this->errors['title'])): ?>
    <span class="error"><?= $this->errors['title'] ?></span>
    <? endif ?>
		<input name="ticket[title]" type="text" value="<?= (isset($this->ticket) ? $this->ticket->title : '') ?>" />

		<label for="ticket[description]"><?= T_('Description') ?></label><br />
		<?= $this->formTextArea('ticket[description]', (isset($this->ticket) ? $this->ticket->description : ''), array('rows' => '15', 'cols' => ' ')) ?><br />

		<label for="ticket[project_id]"><?= T_('Project') ?></label><br />
		<input  name="ticket[project_id]" type="hidden" value="<?= (isset($this->ticket) ? $this->ticket->projectId : $this->project->projects_id) ?>" />
		<?= $this->project->name ?><br />

<?
		$milestonesById = array();
		foreach ($this->milestones as $ms)
			$milestonesById[$ms->id] = $ms->title;
?>
		<label for="ticket[milestone_id]"><?= T_('Milestone') ?></label><br />
		<!-- input  name="ticket[milestone_id]" type="hidden" value="<?= (isset($this->ticket) ? $this->ticket->milestoneId : '') ?>" /><br / -->
		<?= $this->formSelect('ticket[milestone_id]', (isset($this->ticket) ? $this->ticket->milestoneId : ''), array(), $milestonesById); ?><br />

<?
		$usersById = array();
		$table = new USVN_Db_Table_Users();
		$users = $table->fetchAll(null, "users_lastname, users_firstname");
		$usersById[''] = T_('Nobody');
		foreach ($users as $u)
			$usersById[$u->id] = $u->fullname();
?>
		<label for="ticket[assigned_to_id]"><?= T_('Assigned to') ?></label><br />
		<!-- input  name="ticket[milestone_id]" type="hidden" value="<?= (isset($this->ticket) ? $this->ticket->milestoneId : '') ?>" /><br / -->
		<?= $this->formSelect('ticket[assigned_to_id]', (isset($this->ticket) ? $this->ticket->assignedToId : ''), array(), $usersById); ?><br />

		<label for="ticket[status]"><?= T_('Status') ?></label><br />
		<? $opts = array('new' => 'new', 'assigned' => 'assigned', 'closed' => 'closed', 'reopened' => 'reopened') ?>
		<?= $this->formSelect('ticket[status]', (isset($this->ticket) ? $this->ticket->status : ''), array(), $opts); ?><br />

		<label for="ticket[type]"><?= T_('Type') ?></label><br />
		<? $types = Default_Model_Ticket::types() ?>
		<?= $this->formSelect('ticket[type]', (isset($this->ticket) ? $this->ticket->type : ''), array(), $types); ?><br />

		<label for="ticket[priority]"><?= T_('Priority') ?></label><br />
		<? $priorities = Default_Model_Ticket::priorities() ?>
		<?= $this->formSelect('ticket[priority]', (isset($this->ticket) ? $this->ticket->priority : 0), array(), $priorities); ?><br />

    <input type="button" name="" value="<?= T_('Cancel')?>" onClick="document.location.href = '<?= $this->url(array('action' => 'showticket', 'id' => $this->ticket->id), 'roadmap') ?>'" />
		<input type="submit" name="save" value="<?= T_('Save') ?>" />
		<div style="clear:both"></div>
	</form>
</div>
