<div class="usvn_info">
  <h1><?= T_('Roadmap') ?></h1>
</div>
<ul>
<? if (empty($this->milestones)): ?>
  <li><?= T_('No Milestone') ?></li>
<? else: ?>
  <? foreach ($this->milestones as $milestone): ?>
  <li class="milestone">
    <h2><?= h_($milestone->title) ?> <a href="<?= $this->url(array('project' => $this->project->name, 'action' => 'addticket'), 'ticket') ?>"> <?= T_('New Ticket') ?> <?= $this->img('add.png') ?> </a></h2>
    <? $desc = $milestone->description ?>
    <? if (!empty($desc)): ?>
    <p><?= h_($milestone->description) ?> </p>
    <? endif ?>
    <? $tickets = $milestone->tickets ?>
    <? if (empty($tickets)): ?>
    <div style="text-align: center;"><?= T_('No Ticket') ?></div>
    <? else: ?>
    <ul>
      <? foreach ($tickets as $ticket): ?>
      <? $showUrl = $this->url(array('project' => $this->project->name, 'action' => 'showticket', 'id' => $ticket->id), 'ticket') ?>
        <li>
          <a href="<?= $showUrl ?>"><?= $ticket->title ?></a><br />
          <!-- <p>
            type: <?= $ticket->getTypeText() ?><br />
            priority: <?= $ticket->getPriorityText() ?><br />
          </p> -->
        </li>
      <? endforeach ?>
    </ul>
    <? endif ?>
  </li>
  <? endforeach ?>
  <li><a href="<?= $this->url(array('project' => $this->project->name, 'action' => 'addmilestone'), 'ticket') ?>"><?= $this->img('add.png') ?> <?= T_('New Milestone') ?></a></li>
<? endif ?>
</ul>
