<div class="usvn_info">
  <h1><?= T_('Roadmap') ?></h1>
</div>
<ul>
	<li class="shortform">
		<form style="float:right;" action="<?= $this->url(array('project' => $this->project->name, 'action' => 'addmilestone'), 'roadmap') ?>" method="POST">
			<input type="submit" name="" value="<?= T_('create milestone') ?>"></input>
		</form>
<!--		<div style="clear:both;"> </div>-->
	</li>
<? if (empty($this->milestones)): ?>
  <li style="text-align: center"><?= T_('No Milestone') ?></li>
<? else: ?>
  <? foreach ($this->milestones as $milestone): ?>
  <li class="milestone">
    <h2>
    	<a href="<?= $this->url(array('project' => $this->project->name, 'action' => 'milestone', 'id' => $milestone->id), 'roadmap') ?>"><?= h_($milestone->title) ?></a>
    	<form action="<?= $this->url(array('project' => $this->project->name, 'action' => 'addticket'), 'roadmap') ?>" method="POST">
    		<input type="hidden" name="ticket[milestone_id]" value="<?= $milestone->id ?>" />
    		<input type="submit" name="" value="<?= T_('create ticket') ?>"></input>
  		</form>
    </h2>
    <? $due = $milestone->dueDate ?>
    <? if (!empty($due)): ?>
    <p><?= T_('Due') ?> <?= h_($due->toString(Zend_Date::DATE_MEDIUM)) ?> </p>
    <? endif ?>
    <? $tickets = $milestone->tickets ?>
    <? if (empty($tickets)): ?>
    <div style="text-align: center;"><?= T_('No Ticket') ?></div>
    <? else: ?>
    <ul>
      <? foreach ($tickets as $ticket): ?>
      <? $showUrl = $this->url(array('project' => $this->project->name, 'action' => 'showticket', 'id' => $ticket->id), 'roadmap') ?>
        <li>
          <a href="<?= $showUrl ?>"><?= $ticket->title ?></a>
          <span style="float:right"><?= $ticket->typeText ?> - <?= $ticket->priorityText ?><? $this->img($ticket->getPriorityImage()) ?></span>
          <br />
          <!-- <p>
            type: <?= $ticket->getTypeText() ?><br />
            priority: <?= $ticket->getPriorityText() ?><br />
          </p> -->
        </li>
      <? endforeach ?>
    </ul>
    <? endif ?>
  </li>
  <? endforeach ?>
<? endif ?>
</ul>
