<? if ($this->ticket === null): ?>
<div class="error">
  Le Ticket #<?= $this->ticketId ?> n'existe pas
</div>
<? else: ?>
<div class="usvn_info">
  <h1>
    <?= h_($this->ticket->title) ?>
    <? if ($this->ticket->milestoneId): ?>
    (<a href="<?= $this->url(array('action' => 'milestone', 'id' => $this->ticket->milestoneId)) ?>"><?= $this->ticket->milestone->title ?></a>)
    <? endif ?>
    <form style="float:right;" action="<?= $this->url(array('project' => $this->project->name, 'action' => 'editticket', 'id' => $this->ticket->id), 'roadmap') ?>" method="POST">
    	<input type="submit" name="" value="<?= T_('edit') ?>"></input>
    </form>
  </h1>
</div>
<div class="ticket">
  <ul>
    <li>
      <?= T_('Created by') ?> <?= $this->ticket->creator->fullname() ?><br />
      <?= $this->ticket->creationDate->toString(Zend_Date::DATETIME_MEDIUM) ?>
    </li>
    <li>
      <?= T_('Last modification by') ?> <?= $this->ticket->modificator->fullname() ?><br />
      <?= $this->ticket->modificationDate->toString(Zend_Date::DATETIME_MEDIUM) ?>
    </li>
	<? $u = $this->ticket->assignedTo; ?>
	<? if ($u !== null): ?>
	  <li>
      <?= T_('Assigned to') ?> <?= $u->fullname() ?>
    </li>
  <? endif ?>
  </ul>
  <p class="comment">
  	  <?= nl2br(h_($this->ticket->description)) ?>
  </li>
</div>
<? endif ?>
