<?php echo $this->error($this); ?>
<div class="usvn_info">
  <h1><?php echo $this->path ?></h1>
  <br />
  <table width="100%">
    <tr>
      <th align="left"><?php echo T_("Language:")." ".(empty($this->language) ? T_('text') : $this->language) ?></th>
      <th align="right">
        <form method="POST" action="<?php echo $this->url(array('action' => 'browser', 'project' => $this->project->name), 'project') ?>" style="display: inline;">
          <input type="hidden" name="back" value="<?php echo '/'.dirname($this->path).'/' ?>">
          <input type="submit" value="<?php echo T_('Back') ?>" />
        </form>
        /
        <a href="<?php echo USVN_SVNUtils::getSubversionUrl($this->project->name, "/".$this->path) ?>"><?php echo T_('Original') ?></a>
      </th>
    </tr>
    <tr>
      <form name="revisions" method="POST" action="<?php echo $this->url(array('project' => $this->project->name, 'action' => 'show'), 'project')."/".str_replace('%2F', '/', urlencode($this->path)) ?>">
      <td align="center">
          <input type="hidden" name="rev" value="<?php echo $this->revision ?>" id="rev" />
          <?php if ($this->prev_revision > 0) { ?>
            <input type="submit" onclick="document.getElementById('rev').value='<?php echo $this->prev_revision ?>';" value="<?php echo T_('Previous') ?>" />
          <?php } else { ?>
            <input type="submit" value="<?php echo T_('Previous') ?>" disabled />
          <?php } ?>
          <?php echo T_('Revision: ') ?>
          <select onChange="document.getElementById('rev').value=this.value;document.revisions.submit();">
            <?php foreach ($this->select_revisions as $rev) { echo '<option value="'.$rev.'"'.($rev == $this->revision ? 'selected' : '').'>'.$rev.'</option>'; } ?>
          </select>
          <?php if ($this->next_revision > 0) { ?>
            <input type="submit" onclick="document.getElementById('rev').value='<?php echo $this->next_revision ?>';" value="<?php echo T_('Next') ?>" />
          <?php } else { ?>
            <input type="submit" value="<?php echo T_('Next') ?>" disabled />
          <?php } ?>
      </td>
      <td align="left">
        <label><input onChange="document.revisions.submit();" type="checkbox" name="color" style="vertical-align: middle;" <?php echo ($this->color_view ? 'checked' : '') ?> /> <?php echo T_('Color view') ?></label><br />
        <label><input onChange="document.revisions.submit();" type="checkbox" name="diff" style="vertical-align: middle;" <?php echo ($this->diff_view ? 'checked' : '') ?> /> <?php echo T_('Diff view') ?></label>
      </td>
      </form>
    </tr>
  </table>
  <p align="right">
  </p>
</div>
<?php
  if (!$this->diff_view) {
    echo $this->highlighted_source;
  }
  else {
    ?><table border="0" cellspacing="1px" cellpadding="0" width="100%" style="padding: 2px;"><tr><th style="background-color: #EEEEEE;" width="30px;">r<?php echo $this->prev_revision ?></th><th style="background-color: #EEEEEE;" width="30px;">r<?php echo $this->revision ?></th><th style="background-color: #EEEEEE;">&nbsp;</th></tr><?php
      $source = explode("\n", $this->highlighted_source);
      $r1_line = 1;
      $r2_line = 1;
      foreach ($source as $nb => $line) {
        echo '<tr><td align="right" style="background-color: #EEEEEE;">';
        if (!isset($this->diff_lines[$nb]) || $this->diff_lines[$nb] == '-') {
          echo $r1_line++;
        } else {
          echo '&nbsp;';
        }
        echo '</td><td align="right" style="background-color: #EEEEEE;">';
        if (!isset($this->diff_lines[$nb]) || $this->diff_lines[$nb] == '+') {
          echo $r2_line++;
        } else {
          echo '&nbsp;';
        }
        echo '</td>';
        if (isset($this->diff_lines[$nb])) {
          echo '<td style="background-color: '.($this->diff_lines[$nb] == '+' ? '#DDFFDD' : '#FFDDDD').';">';
        }
        else {
          echo '<td>';
        }
        echo $line, '</td></tr>';
      }
    ?></table><?php
  }
?>