<? if ($this->ticket === null): ?>
<div class="error">
  Le Ticket #<?= $this->ticketId ?> n'existe pas
</div>
<? else: ?>
<div class="usvn_info">
  <h1>
    <?= h_($this->ticket->title) ?>
    <? if ($this->ticket->milestoneId): ?>
    (<a href="<?= $this->url(array('action' => 'milestone', 'id' => $this->ticket->milestoneId)) ?>"><?= h_($this->ticket->milestone->title) ?></a>)
    <? endif ?>
    <form style="float:right;" action="<?= $this->url(array('project' => $this->project->name, 'action' => 'editticket', 'id' => $this->ticket->id), 'roadmap') ?>" method="POST">
    	<input type="submit" name="" value="<?= T_('edit') ?>"></input>
    </form>
  </h1>
</div>
<div class="ticket">
  <ul>
    <li>
        <p style="font-weight: bold;"><?= T_('Created by') ?> <?= $this->ticket->creator->fullname() ?></p>
        &nbsp;&nbsp;&nbsp;<?= $this->ticket->creationDate->toString(Zend_Date::DATETIME_MEDIUM) ?>
    </li>
    <p style="border-bottom: 1px dashed silver;"></p>
    <li>
        <p style="font-weight: bold;"><?= T_('Last modification by') ?> <?= $this->ticket->modificator->fullname() ?></p>
        &nbsp;&nbsp;&nbsp;<?= $this->ticket->modificationDate->toString(Zend_Date::DATETIME_MEDIUM) ?>
    </li>
    <? $u = $this->ticket->assignedTo; ?>
    <? if ($u !== null): ?>
        <p style="border-bottom: 1px dashed silver;"></p>
        <li>
            <p style="font-weight: bold;"><?= T_('Assigned to') ?> <?= $u->fullname() ?></p>
        </li>
  <? endif ?>
  </ul>
  <p class="comment">
  	  <?= nl2br(h_($this->ticket->description)) ?>
  </li>
</div>
<? endif ?>
