<div class="usvn_info">
  <h1><?= T_('Roadmap') ?></h1>
</div>
	<style>
	a.atd {
	display: block;
	width: 100%;
	height: 100%;
}
	</style>
<table border="0" cellspacing="0" cellpadding="0" class="sortable">
	<thead>
    <tr>
    	<th><?= T_('Title') ?></th>
    	<th><?= T_('Created') ?></th>
    	<th><?= T_('Edited') ?></th>
    	<th><?= T_('Type')?></th>
    	<th><?= T_('Status')?></th>
    	<th><?= T_('Priority')?></th>
    	<th></th>
    </tr>
	</thead>
	<tbody>
		<? if (count($this->tickets) == 0): ?>
    <tr class=""><td colspan="7">Aucun Ticket</td></tr>
		<? else: ?>
    <? $even = true ?>
    <? foreach ($this->tickets as $ticket): ?>
    <? $even = !true ?>
    <? $showUrl = $this->url(array('project' => $this->project->name, 'action' => 'showticket', 'id' => $ticket->id), 'ticket') ?>
    <tr class="<?= $even ? 'even' : 'odd' ?>">
        <td><a class="atd" href="<?= $showUrl ?>"><?= h_($ticket->title) ?> </a></td>
	      <td><a class="atd" href="<?= $showUrl ?>"><?= $ticket->creationDate->toString(Zend_Date::DATETIME_SHORT) ?> </a></td>
  	    <td><a class="atd" href="<?= $showUrl ?>"><?= $ticket->modificationDate->toString(Zend_Date::DATETIME_SHORT) ?> </a></td>
    	  <!-- td><a class="atd" href="<?= $showUrl ?>"><?= h_($ticket->description) ?></a></td -->
      	<td><a class="atd" href="<?= $showUrl ?>"><?= h_($ticket->type) ?>&nbsp;</a></td>
        <td><a class="atd" href="<?= $showUrl ?>"><?= h_($ticket->status) ?>&nbsp;</a></td>
	      <td><a class="atd" href="<?= $showUrl ?>"><?= h_($ticket->getPriorityText()) ?>&nbsp;</a></td>
	      <td><?= $this->urlConfirm(array('controller' => 'project', 'action' => 'deleteticket', 'project' => $this->project->name , 'id' => $ticket->id), $this->img('delete.png'), sprintf('pwet %s', $ticket->title), 'ticket') ?></td>
<!--	      <td><a href="<?= $this->url(array('project' => $this->project->name, 'action' => 'deleteticket', 'id' => $ticket->id), 'ticket') ?>">Link Text </a></td>-->
    </tr>
    <? endforeach ?>
    <? endif ?>
	</tbody>
  <tfoot>
	  <tr class="" style="text-align: right;">
	  	<th colspan="7"><a href="<?= $this->url(array('project' => $this->project->name, 'action' => 'addticket'), 'ticket') ?>"><?= T_('Nouveau') ?><?= $this->img('add.png') ?></a></th>
	  </tr>
  </tfoot>
</table>
