<?= $this->error($this) ?>
 <div class="usvn_info">
    <h1><?= T_("Timeline") ?> </h1>
</div>
<div class="usvn_info">
    <form action="<?= $this->url(array("action" => "LastHundredRequest")) ?>" method="post">
        <div>
            <table>
                <tr>
                    <td>
                        <a href="#" class="usvn_tooltips">
                            <?= T_("Start (revision number or date)") ?>
                            <span>
                                <?= T_("You can list 100 revisions since your revision or date. The date format is : DD/MM/YYYY") ?>
                            </span>
                        </a>:
                    </td>
                    <td>
                        <?= $this->formText('number_start', $this->number_start) . '<br />' ?>
                     </td>
                 </tr>
                 <tr>
                     <td>
                    <a href="#" class="usvn_tooltips">
                        <?= T_('End (revision number or date)') ?>
                        <span>
                            <?= T_('This is optional.The listing is made between start revision/date and this one.') ?>
                        </span>
                    </a>:
                    </td>
                    <td>
                        <?= $this->formText('number_end', $this->number_end) ?>
                    </td>
                </tr>
                <tr>
                    <td>
                        <?= $this->formSubmit('LastHundredRequest', T_('Search')) ?>
                    </td>
                </tr>
            </table>
        </div>
    </form>
</div>
<div class="usvn_info">
    <?php $date = NULL; ?>
    <? foreach (array_keys($this->log) as $revision): ?>
        <?php $commit = $this->log[$revision];
            $zdate = (empty($commit['date']) ? null : new Zend_Date($commit['date']));
            if ($date == NULL or strcmp($date, date('Y-m-d',  $commit['date'])) != 0)
            {
                if ($zdate !== null)
                {
                    $date = date('Y-m-d',  $commit['date']);
                    echo '<div class="commit-date">' . $zdate->toString(Zend_Date::DATES) . ':</div>';
                }
            }
            echo '<span class="commit"><a href="' .
                    $this->url(array(
                        'project' => $this->project->name,
                        'action' => 'commit',
                        'commit' => $revision),
                        'commit'
                        ) . '"><span class="commit-time">' .
                    //date('H:i',  $commit['date']) .
                    ($zdate !== null ? $zdate->toString(Zend_Date::TIME_SHORT) : '-' ) . 
                    '</span><span class="commit-black">Changeset</span> [' . $revision . '] <span class="commit-black">by</span> <span class="commit-author">' .
                    $commit['author'] . '</span></a></span>';
            echo '<p class="commit-message">' . USVN_SVNLog::formatComment($commit['msg']) . '</p>';
        ?>
    <? endforeach ?>
</div>
