<div class="usvn_info">
	<h1><?= T_("Welcome to USVN")?></h1>
	<p>
		<?= T_("Please enter your login and your password to connect to USVN.") ?>
	</p>
</div>
<div>
	<form method="post" action="<?= $this->url() ?>">
		<div id="box">
			<label for="login" id="username"><?= T_("Login") ?><br />
				<?= $this->formText('login', (isset($this->login) ? $this->login : "")) ?>
			</label>
			<br />
			<label for="lbPass" id="pass">
				<?= T_("Password") ?><br />
				<?= $this->formPassword('password') ?>
			</label>
			<br />
			<?= $this->formSubmit('submit', T_("Submit")) ?>
		</div>
	</form>
</div>
