<div class="usvn_info">
	<h1><?= T_("Welcome to USVN")?></h1>
	<p>
		<?= T_("Please enter your login and your password to connect to USVN.") ?>
	</p>
</div>
<div>
	<form method="post" action="<?= $this->url() ?>">
		<table id="login_box">
			<tr id="username">
				<td id="lbLogin"><?= T_("Login") . ':' ?></td>
				<td><?= $this->formText('login', (isset($this->login) ? $this->login : "")) ?></td>
			</tr>
			<tr id="pass">
				<td id="lbPass"><?= T_("Password") . ':' ?></td>
				<td><?= $this->formPassword('password') ?></td>
			</tr>
			<tr id="logon">
				<td colspan="2"><?= $this->formSubmit('submit', T_("Submit")) ?></td>
			</tr>
		</table>
	</form>
</div>
