<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html>
<?php $view = $this->layout()->getView(); ?>
	<head>
		<meta http-equiv="Content-type" content="text/html; charset=utf-8">
		<?php $config = Zend_Registry::get("config"); ?>

		<title><?php echo $config->site->title ?></title>
		<link type="text/css" rel="stylesheet" media="screen" href="<?php echo $this->url(array('action' => 'screen'), 'css'); ?>" />
		<link rel="shortcut icon" href="<?php echo $config->url->base . '/' . $config->site->ico ?>" />

		<script type="text/javascript" src="<?php echo $this->url(array(), 'js'); ?>"></script>

		<?php if (isset($view->csss)): foreach ($view->csss as $css): ?>
		  <link type="text/css" rel="stylesheet" media="screen" href="<?php echo $this->url(array('type' => 'css', 'media' => $config->template->name, 'name' => $css), 'medias'); ?>" />
		<?php endforeach; endif; ?>

		<?php if (isset($view->javascripts)): foreach ($view->javascripts as $js): ?>
		  <script type="text/javascript" src="<?php echo $this->url(array('type' => 'js', 'media' => $config->template->name, 'name' => $js), 'medias'); ?>"></script>
		<?php endforeach; endif; ?>

	</head>
	<body>
		<div id="header">
			<div id="shaddow">
				<div id="header-wrapper">
					<a href="<?php echo $this->url(array(), 'default', true); ?>">
						<div id="logo" style="background: transparent url('<?php echo $config->url->base . '/' . $config->site->logo ?>') no-repeat 0px 0px;"></div>
					</a>
					<div id="main-menu">
						<ul>
							<?php if ($this->isLogged): ?>
							<?php
								$array = array();
								$array['index'] = T_('Home');
								$array['profile'] = T_('Profile');
								if ($this->isAdmin)
									$array['admin'] = T_('Admin');
								$array['logout'] = T_('Logout') . ' (' . $this->login . ')';
								foreach ($array as $menuLink => $menuLabel): ?>
									<li><a href="<?php echo $this->url(array('controller' => $menuLink), 'default', true) ?>" <?php echo ($menuLink == $this->area ? ' id="selected"' : ''); ?>><span><?php echo T_($menuLabel); ?></span></a></li>
								<?php endforeach; ?>
							<?php endif; ?>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div id="container">
			<div id="container-wrapper">
				<?php if (!empty($this->layout()->getView()->submenu)): ?>
					<div id="sub-menu">
						<ul>
							<?php foreach($this->layout()->getView()->submenu as $item): ?>
								<li>
									<?php if (isset($item['href'])): ?>
										<a href="<?php echo htmlspecialchars($this->url(array('controller' => ''), 'default', true) . $item['href']); ?>">
											<?php echo htmlspecialchars(T_($item['label'])); ?>
										</a>
									<?php elseif (isset($item['url'])): ?>
										<?php $route = (isset($item['route']) ? $item['route'] : null); ?>
										<a href="<?php echo htmlspecialchars($this->url($item['url'], $route, true)); ?>">
											<?php echo htmlspecialchars(T_($item['label'])); ?>
										</a>
									<?php else: ?>
										<h3><?php echo T_($item['label']); ?></h3>
									<?php endif; ?>
								</li>
							<?php endforeach; ?>
						</ul>
					</div>
				<?php endif; ?>
				<div id="main">
					<?php echo $this->layout()->content ?>
					<div style="clear:both;"></div>
				</div>
				<div id="hspacer">
					&nbsp;
				</div>
				<div id="footer">
					Footer
	  		</div>
			</div>
		</div>
	</body>
</html>
