<?php
/**
 * Class who handle subversion hooks via XML-RPC
 *
 * @author Team USVN <contact@usvn.info>
 * @link http://www.usvn.info
 * @license http://www.cecill.info/licences/Licence_CeCILL_V2-en.txt CeCILL V2
 * @copyright Copyright 2007, Team USVN
 * @since 0.5
 * @package svnhooks
 * @subpackage model
 *
 * This software has been written at EPITECH <http://www.epitech.net>
 * EPITECH, European Institute of Technology, Paris - FRANCE -
 * This project has been realised as part of
 * end of studies project.
 *
 * $Id$
 */
// Call USVN_modules_svnhooks_models_HooksTest::main() if this source file is executed directly.
if (!defined("PHPUnit_MAIN_METHOD")) {
    define("PHPUnit_MAIN_METHOD", "USVN_modules_svnhooks_models_HooksTest::main");
}

require_once "PHPUnit/Framework/TestCase.php";
require_once "PHPUnit/Framework/TestSuite.php";

require_once 'www/USVN/autoload.php';

/**
 * Test class for USVN_modules_svnhooks_models_Hooks.
 * Generated by PHPUnit_Util_Skeleton on 2007-03-10 at 19:20:07.
 */
class USVN_modules_svnhooks_models_HooksTest extends PHPUnit_Framework_TestCase {
    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main() {
        require_once "PHPUnit/TextUI/TestRunner.php";

        $suite  = new PHPUnit_Framework_TestSuite("USVN_modules_svnhooks_models_HooksTest");
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

  public function test_startCommit()
    {
		$hook = new USVN_modules_svnhooks_models_Hooks();
		$hook->startCommit("007", "test");
    }

    public function test_preCommit()
    {
		$hook = new USVN_modules_svnhooks_models_Hooks();
		$hook->preCommit("007", "test", "Ceci est un commit", array(array('M', 'tata'), array('A', 'tutu')));
    }

    public function test_postCommit()
    {
		$hook = new USVN_modules_svnhooks_models_Hooks();
		$hook->postCommit("007", 1, "test", "Ceci est un commit", array(array('M', 'tata'), array('A', 'tutu')));
    }

    public function test_preLock()
    {
		$hook = new USVN_modules_svnhooks_models_Hooks();
		$hook->preLock("007", "tutu", "test");
    }

    public function test_postLock()
    {
		$hook = new USVN_modules_svnhooks_models_Hooks();
		$hook->postLock("007", "tutu", "test");
    }

    public function test_preUnlock()
    {
		$hook = new USVN_modules_svnhooks_models_Hooks();
		$hook->preUnlock("007", "tutu", "test");
    }

    public function test_postUnlock()
    {
		$hook = new USVN_modules_svnhooks_models_Hooks();
		$hook->postUnlock("007", "tutu", "test");
    }

    public function test_preRevpropChange()
    {
		$hook = new USVN_modules_svnhooks_models_Hooks();
		$hook->preRevpropChange("007", 1, "test", "svn:log", "M", "message de log");
    }

    public function test_postRevpropChange()
    {
		$hook = new USVN_modules_svnhooks_models_Hooks();
		$hook->postRevpropChange("007", 1, "test", "svn:log", "M", "message de log");
    }

	public function test_validUSVNServer()
    {
		$hook = new USVN_modules_svnhooks_models_Hooks();
		$this->assertTrue($hook->validUSVNServer("007"));
    }
}

// Call USVN_modules_svnhooks_models_HooksTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == "USVN_modules_svnhooks_models_HooksTest::main") {
    USVN_modules_svnhooks_models_HooksTest::main();
}
?>
