<?php
// Call USVN_Auth_Adapter_DbTest::main() if this source file is executed directly.
if (!defined("PHPUnit_MAIN_METHOD")) {
	define("PHPUnit_MAIN_METHOD", "USVN_Auth_Adapter_DbTest::main");
}

require_once "PHPUnit/Framework/TestCase.php";
require_once "PHPUnit/Framework/TestSuite.php";

require_once 'USVN/autoload.php';

/**
 * Test class for USVN_Auth_Adapter_Db.
 * Generated by PHPUnit_Util_Skeleton on 2007-03-10 at 17:19:58.
 */
class USVN_Auth_Adapter_DbTest extends PHPUnit_Framework_TestCase {
	/**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
	public static function main() {
		require_once "PHPUnit/TextUI/TestRunner.php";

		$suite  = new PHPUnit_Framework_TestSuite("USVN_Auth_Adapter_DbTest");
		$result = PHPUnit_TextUI_TestRunner::run($suite);
	}

	/**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
	protected function setUp() {
		$stub = $this->getMock('Zend_Db_Adapter_Pdo_Mysql', array(), array(array('dbname' => 'mockme')));
		$stub->expects($this->any())
			->method('desribeTable')
			->will($this->returnValue(array('user_id', 'user_login', 'user_password')));

		require_once 'Zend.php';
		Zend::dump($stub->describeTable('users'));
		Zend_Db_Table::setDefaultAdapter($stub);
	}

	/**
     * Tears down the fixture, for example, close a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
	protected function tearDown() {
	}

	/**
     * @todo Implement testAuthenticate().
     */
	public function testAuthenticateCannotPerformWithoutParameters() {
		$auth = new USVN_Auth_Adapter_Db('', '');
		$ret = $auth->authenticate();
	}

	public function testAuthenticateCannotPerformWithoutParameters2() {
	}
	public function testAuthenticateCannotPerformWithoutParameters3() {
	}
}

// Call USVN_Auth_Adapter_DbTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == "USVN_Auth_Adapter_DbTest::main") {
	USVN_Auth_Adapter_DbTest::main();
}
?>
