<?php
// Call USVN_Db_Table_Row_GroupTest::main() if this source file is executed directly.
if (!defined("PHPUnit_MAIN_METHOD")) {
    define("PHPUnit_MAIN_METHOD", "USVN_Db_Table_Row_GroupTest::main");
}

require_once "PHPUnit/Framework/TestCase.php";
require_once "PHPUnit/Framework/TestSuite.php";

require_once 'www/USVN/autoload.php';


/**
 * Test class for USVN_Db_Table_Row_Group.
 * Generated by PHPUnit_Util_Skeleton on 2007-04-18 at 14:39:49.
 */
class USVN_Db_Table_Row_GroupTest extends USVN_Test_DB {
	private $groupTable;
	private $group;
	private $groupid;
	private $users;

	/**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main() {
        require_once "PHPUnit/TextUI/TestRunner.php";

        $suite  = new PHPUnit_Framework_TestSuite("USVN_Db_Table_Row_GroupTest");
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    public function setUp() {
		parent::setUp();
		$this->groupTable = new USVN_Db_Table_Groups();
		$this->group = $this->groupTable->fetchNew();
		$this->group->groups_name = 'test';
		$this->groupid = $this->group->save();

		$this->users = new USVN_Db_Table_Users();
		$user = $this->users->insert(
			array(
				"users_id" => 2,
				"users_login" => "test",
				"users_password" => USVN_Crypt::crypt("test")
			)
		);
		$this->users->insert(
			array(
				"users_id" => 3,
				"users_login" => "babar",
				"users_password" => USVN_Crypt::crypt("test")
			)
		);
		$this->users->insert(
			array(
				"users_id" => 4,
				"users_login" => "john",
				"users_password" => USVN_Crypt::crypt("test")
			)
		);
    }

	public function testGroup()
	{
		$this->assertEquals('test', $this->group->groups_name);
		$this->assertEquals('test', $this->group->name);
	}

	public function testAddUser()
	{
		$this->group->addUser($this->users->find(2)->current());
		$this->group->addUser($this->users->find(3)->current());
		$this->users = $this->group->findManyToManyRowset('USVN_Db_Table_Users', 'USVN_Db_Table_UsersToGroups');
		$res = array();
		foreach ($this->users as $user) {
			array_push($res, $user->users_login);
		}
		$this->assertContains("test", $res);
		$this->assertContains("babar", $res);
		$this->assertNotContains("john", $res);
	}

	public function testUserIsMember()
	{
		$user = $this->users->find(2)->current();
		$this->assertFalse($this->group->userIsMember($user));
		$this->group->addUser($user);
		$this->assertTrue($this->group->userIsMember($user));
	}
}

// Call USVN_Db_Table_Row_GroupTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == "USVN_Db_Table_Row_GroupTest::main") {
    USVN_Db_Table_Row_GroupTest::main();
}
?>
