<script type="text/javascript">
HTMLTableToolsOptions.multiColSort = false;
HTMLTableToolsOptions.showSortIndex = false;
HTMLTableToolsOptions.skipCells = [3];
</script>
<div class="usvn_info_group">
	<h1><?php echo T_("Groups"); ?></h1>
</div>
<?php
print '<table class="sortable" id="groups">' .
		'<thead><tr>' .
		'<th>' . T_('Name') . '</th>' .
		'<th>' . T_('Description') . '</th>' .
		'<th>' . T_('Action') . '</th>' .
		'</tr></thead><tbody>';

if (count($this->groups)) {
	foreach ($this->groups as $group) {
		$editurl = $this->url(array('action' => 'edit', 'name' => $group->name));
		$deletetext = T_("Do you really want to delete group %s?");
		$line = <<<EOF
		<tr>
			<td>
				<a href="{$editurl}">{$group->name}</a>
			</td>
			<td>
				<a href="{$editurl}">{$group->description}</a>
			</td>
			<td>
                {$this->editLink('name', $group->name)}
                {$this->deleteLink('name', $group->name, $deletetext)}
            </td>
		</tr>\n
EOF;
		echo $line;
	}
}
print '</tbody></table><br />';
?>
