<?php
// Call USVN_Db_UtilsTest::main() if this source file is executed directly.
if (!defined("PHPUnit_MAIN_METHOD")) {
    define("PHPUnit_MAIN_METHOD", "USVN_Db_UtilsTest::main");
}

require_once "PHPUnit/Framework/TestCase.php";
require_once "PHPUnit/Framework/TestSuite.php";

require_once 'www/USVN/autoload.php';

/**
 * Test class for USVN_Db_Utils.
 * Generated by PHPUnit_Util_Skeleton on 2007-03-13 at 16:30:24.
 */
class USVN_Db_UtilsTest extends PHPUnit_Framework_TestCase {
    private $testfile = "tests/tmp/db.sql";

	/**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main() {
        require_once "PHPUnit/TextUI/TestRunner.php";

        $suite  = new PHPUnit_Framework_TestSuite("USVN_Db_UtilsTest");
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    public function setUp() {
		$params = array ('host'     => 'localhost',
                 'username' => 'usvn-test',
                 'password' => 'usvn-test',
                 'dbname'   => 'usvn-test');

		$this->db = Zend_Db::factory('PDO_MYSQL', $params);
		Zend_Db_Table::setDefaultAdapter($this->db);
		USVN_Db_Utils::deleteAllTables($this->db);

		file_put_contents($this->testfile,
		"
		/*==============================================================*/
		/* Table: users                                                 */
		/*==============================================================*/
		create table users
		(
		   users_id                       int                            not null,
		   users_login                    varchar(255)                   not null,
		   users_password                 varchar(44)                    not null,
		   users_nom                      varchar(100),
		   users_prenom                   varchar(100),
		   users_email                    varchar(150),
		   primary key (users_id)
		)
		type = innodb;

		/*==============================================================*/
		/* Table: groups                                                */
		/*==============================================================*/
		create table groups
		(
		   groups_id                      int                            not null,
		   groups_label                   varchar(100),
		   groups_nom                     varchar(150),
		   primary key (groups_id)
		)
		type = innodb;

		/*==============================================================*/
		/* Table: to_belong                                             */
		/*==============================================================*/
		create table to_belong
		(
		   users_id                       int                            not null,
		   groups_id                      int                            not null,
		   primary key (users_id, groups_id)
		)
		type = innodb;

		/*==============================================================*/
		/* Index: to_belong_fk                                          */
		/*==============================================================*/
		create index to_belong_fk on to_belong
		(
			users_id
		);

		/*==============================================================*/
		/* Index: to_belong2_fk                                         */
		/*==============================================================*/
		create index to_belong2_fk on to_belong
		(
			groups_id
		);

		alter table to_belong add constraint fk_to_belong foreign key (users_id)
		references users (users_id) on delete restrict on update restrict;

		alter table to_belong add constraint fk_to_belong2 foreign key (groups_id)
		references groups (groups_id) on delete restrict on update restrict;
		");
    }

    protected function tearDown() {
		USVN_Db_Utils::deleteAllTables($this->db);
		unlink($this->testfile);
    }

    public function testLoadFile() {
		USVN_Db_Utils::loadFile($this->db, $this->testfile);
		$this->assertEquals(3, sizeof($this->db->listTables()));
    }

	public function test_deleteAllTables()
	{
		USVN_Db_Utils::loadFile($this->db, $this->testfile);
		$this->assertEquals(3, sizeof($this->db->listTables()));
		USVN_Db_Utils::deleteAllTables($this->db);
		$this->assertEquals(0, sizeof($this->db->listTables()));
	}
}

// Call USVN_Db_UtilsTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == "USVN_Db_UtilsTest::main") {
    USVN_Db_UtilsTest::main();
}
?>
