<?php

echo $this->error($this);
include dirname(__FILE__) . DIRECTORY_SEPARATOR . 'js.phtml';
?>
<form id="user" name="user" class="usvn_form" method="post" action="<?php echo $this->url(array("action" => "update")) ?>">
<?php

include dirname(__FILE__) . DIRECTORY_SEPARATOR . "form.phtml";

?>
		<br />
		<?php echo $this->formSubmit('submit', T_("Submit"), array("onclick" => 'return checkForm();')); ?>
		<br />
	</fieldset>
</form>
<br />
