<div class="usvn_info">
	<h1><?= T_("Projects") ?> <?= ($this->prefix != null ? '('.$this->prefix.')' : '') ?></h1>
</div>
<table class="sortable" id="projects">
	<thead>
		<tr>
			<th><?= T_('Name') ?></th>
			<th><?= T_('Description') ?></th>
			<th class="sorttable_nosort" width="112px"><?= T_('Action') ?></th>
		</tr>
	</thead>
	<tbody>
	
	<? if (!empty($this->projects)): ?>
	<? $deletetext = T_("Do you really want to delete project %s?"); ?>
	<?php if ($this->prefix != null): ?>
	  <tr>
      <td><a href="<?= $this->url(array('action' => 'index', 'folder' => $this->prev)); ?>">
        <span class="grid_img">
					<?= $this->img('folder.png') ?>
				</span>
        ..
      </a></td><td>&nbsp;</td><td>&nbsp;</td>
    </tr>
	<?php endif ?>
	<? foreach ($this->projects as $project => $datas): ?>
	  <?php if (substr($project, -1) == DIRECTORY_SEPARATOR): ?>
	    <tr>
        <td><a href="<?= $this->url(array('action' => 'index', 'folder' => $this->prefix.$project)); ?>">
          <span class="grid_img">
  					<?= $this->img('folder.png') ?>
  				</span>
          <?= $project ?>
        </a></td><td>&nbsp;</td><td>&nbsp;</td>
      </tr>
    <?php else: ?>
      <? $editurl = $this->url(array('controller' => 'project', 'action' => 'edit', 'name' => $this->prefix.$project), 'admin', true); ?>
      <tr>
        <td><a href="<?= $this->url(array('action' => null, 'project' => $this->prefix.$project), 'project', true) ?>">
          <span class="grid_img">
  					<?= $this->img('box24.png') ?>
  				</span>
          <?= $project ?>
        </a></td>
        <td><a href="<?= $editurl ?>"><?= nl2br(htmlspecialchars($datas)) ?></a></td>
        <td class="align-right">
          <?= $this->homeLink($this->prefix.$project) ?>
          <?= $this->editLink('project', 'name', $this->prefix.$project) ?>
          <?= $this->deleteLink('project', 'name', $this->prefix.$project, $deletetext) ?>
          <?= $this->ACLLink($this->prefix.$project) ?>
        </td>
      </tr>
    <?php endif ?>
	<? endforeach ?>
	<? endif ?>
	</tbody>
	<tfoot>
		<tr>
			<td colspan="3" class="align-right">
				<a href="<?= $this->url(array('action' => 'new')) ?>"><?= T_("New Project") ?></a>
				<?= $this->addLink() ?>
			</td>
		</tr>
	</tfoot>
</table>
<br />
