<div class="usvn_info">
	<h1>
		<?= T_("Project's information"); ?>
	</h1>
</div>

<?php echo $this->error($this); ?>

<script type="text/javascript">
<!--
function checkName()
{
	var spanError = document.getElementById('error');
	var checkRegExp = new RegExp("^[ \t]*$");
	var project = document.getElementById('project');
	if (project.projects_name.value.length == 0 || checkRegExp.test(project.projects_name.value))
	{
		spanError.innerHTML = "<?php echo T_('Project\'s name empty, please fill it.'); ?>;"
		spanError.className = "usvn_error";
		return false;
	}
	spanError.innerHTML = '';
	spanError.className = "";
	return true;
}
-->
</script>

<div id="profile">
<?php
$this->url = $this->url(array("action" => "create"));
include dirname(__FILE__) . DIRECTORY_SEPARATOR . "form.phtml";
?>
</div>
