#!/bin/sh -e

. /usr/share/debconf/confmodule



chown www-data:www-data /var/lib/usvn
chown www-data:www-data /var/lib/svn
chown www-data:www-data /etc/usvn/config.ini
chmod 600 /etc/usvn/config.ini
#DEBHELPER#

#Get USVN admin user
db_get usvn-sqlite/user
USER=$RET
db_get usvn-sqlite/password
PASSWORD=$RET
cd /usr/share/usvn/
php install/install-commandline.php /etc/usvn.config.ini /usr/share/usvn/.htaccess $USER $PASSWORD || exit 1
