<div class="usvn_info">
	<h1><?php echo T_("Administration"); ?></h1>
	<?php echo T_("USVN version: "), $this->config->version;?>
</div>
<?php if ($this->config->version != $this->available_version) {?>
<div class="usvn_update">
	<?php echo sprintf(T_("Your version of USVN is out of date. A new version %s is available on
	<a href=\"http://www.usvn.info\">http://www.usvn.info</a>."), $this->available_version); ?>
</div>
<?php } ?>
<ul id="usvn_admin_section">
	<li>
		<a href="<?php echo $this->url(array('controller' => 'user'));?>">
			<?php echo $this->img("user.png");?>
			<?php echo T_("Users");?>
		</a>
	</li>
	<li>
		<a href="<?php echo $this->url(array('controller' => 'group'));?>">
			<?php echo $this->img("group.png");?>
			<?php echo T_("Groups");?>
		</a>
	</li>
	<li>
		<a href="<?php echo $this->url(array('controller' => 'project'));?>">
			<?php echo $this->img("box32.png");?>
			<?php echo T_("Projects");?>
		</a>
	</li>
	<li>
		<a href="<?php echo $this->url(array('controller' => 'config'));?>">
			<?php echo $this->img("config.png");?>
			<?php echo T_("Configuration");?>
		</a>
	</li>
</ul>

