<div class="usvn_info">
	<h1><?php echo T_("Administration"); ?></h1>
	<?php echo T_("USVN version: "), $this->config->version;?>
</div>
<?php if (strcmp($this->config->version, $this->available_version) < 0) {?>
<div class="usvn_update">
	<?php echo sprintf(T_("Your version of USVN is out of date. A new version %s is available on
	<a href=\"http://www.usvn.info\">http://www.usvn.info</a>."), $this->available_version); ?>
</div>
<?php } ?>
<ul id="usvn_admin_section">
	<li>
		<a href="<?php echo $this->url(array('controller' => 'user'));?>">
			<?php echo $this->img("user.png");?><br />
			<span><?php echo T_("Users");?></span>
		</a>
	</li>
	<li>
		<a href="<?php echo $this->url(array('controller' => 'group'));?>">
			<?php echo $this->img("group32.png");?><br />
			<span><?php echo T_("Groups");?></span>
		</a>
	</li>
	<li>
		<a href="<?php echo $this->url(array('controller' => 'project'));?>">
			<?php echo $this->img("box32.png");?><br />
			<span><?php echo T_("Projects");?></span>
		</a>
	</li>
	<li>
		<a href="<?php echo $this->url(array('controller' => 'config'));?>">
			<?php echo $this->img("config.png");?><br />
			<span><?php echo T_("Configuration");?></span>
		</a>
	</li>
</ul>

