<div class="usvn_info_config">
	<h1><?php echo T_("Administration"); ?></h1>
	<?php echo T_("USVN version: "), $this->config->version;?>
</div>
<ul id="usvn_admin_section">
	<li>
		<a href="<?php echo $this->url(array('controller' => 'config'));?>">
			<?php echo $this->img("CrystalClear/64x64/apps/kpackage.png");?>
			<?php echo T_("Configuration");?>
		</a>
	</li>
	<li>
		<a href="<?php echo $this->url(array('controller' => 'project'));?>">
			<?php echo $this->img("CrystalClear/64x64/apps/easymoblog.png");?>
			<?php echo T_("Projects");?>
		</a>
	</li>
	<li>
		<a href="<?php echo $this->url(array('controller' => 'group'));?>">
			<?php echo $this->img("CrystalClear/64x64/apps/Community Help.png");?>
			<?php echo T_("Groups");?>
		</a>
	</li>
	<li>
		<a href="<?php echo $this->url(array('controller' => 'user'));?>">
			<?php echo $this->img("CrystalClear/64x64/apps/kdmconfig.png");?>
			<?php echo T_("Users");?>
		</a>
	</li>
</ul>

