<div class="usvn_info">
	<h1><?= T_("Hooks") ?></h1>
</div>

<table class="sortable" id="hooks">
	<thead>
		<tr>
			<th><?= T_('Path') ?></th>
			<th><?= T_('Type') ?></th>
			<th class="sorttable_nosort" width="56px"><?= T_('Action') ?></th>
		</tr>
	</thead>
	<tbody>

<? if (!empty($this->hooks)): ?>
	<? $even = true ?>
	<? foreach ($this->hooks as $hook): ?>
		<? $even = !$even ?>
    <tr class="<?= ($even ? 'even' : 'odd') ?>">
      <? $deletetext = T_("Do you really want to delete hook %s?") ?>
      <? $editurl = $this->url(array('action' => 'edit', 'id' => $hook->id)) ?>
      <td><a href="<?= h_($editurl) ?>"><?= h_($hook->path) ?></a></td>
      <td><a href="<?= h_($editurl) ?>"><?= h_($hook->event) ?></a></td>
      <td class="align-right">
        <?= $this->editLink('hooks', 'id', $hook->id) ?>
        <?= $this->deleteLink('hooks', 'id', $hook->id, $deletetext) ?>
      </td>
    </tr>
	<? endforeach ?>
<? endif ?>
	</tbody>
	<tfoot>
		<tr>
			<td colspan="6" class="align-right">
				<div>
					<a href="<?= $this->url(array('action' => 'new')) ?>"><?= T_("Manage active hooks") ?></a>
					<?= $this->addLink() ?>
				</div>
			</td>
		</tr>
	</tfoot>
</table>
<br />
