 <?php echo $this->error($this); ?>
 <div class="usvn_info">
<h1><?php echo T_("Enter your number of revision or date");?> </h1>
	<form style="float: left; text-align: left;" action="<?php echo $this->url(array("action" => "LastHundredRequest")); ?>" method="post">
			<div>
				<table>
					<tr>
						<td>
							<?php					
							 echo $this->formText("number_start"); 
							 echo '<br>';
							 echo $this->formText("number_end"); ?>
						</td>
						<td>
							<?php echo $this->formSubmit("LastHundredRequest", T_("Search")); ?>
						</td>
					</tr>
					<tr>
						<td>
							
						</td>
						<td>
						</td>
					</tr>
				</table>
			</div>
		</form>		
</div>

<div class="usvn_info">
	<h1><?php echo T_("Last hundred commit");?></h1>
	<table id="commits" class="sortable">
		<thead>
			<tr>
				<th><?php echo T_("Revision");?></th>
				<th><?php echo T_("Author");?></th>
				<th><?php echo T_("Date");?></th>
				<th><?php echo T_("Message");?></th>
			</tr>
		</thead>
		<tbody>
		<?php
			foreach (array_keys($this->log) as $revision) {
				$commit = $this->log[$revision];
				echo "<tr><td>{$revision}</td><td>{$commit['author']}</td><td>" . date("Y-m-d",  $commit["date"]) . "&nbsp;" . date("H:i", $commit["date"]) . "</td><td>" . nl2br($commit['msg']) . "</td></tr>";
			}
		?>
		</tbody>
	</table>
</div>