<?php
// Call USVN_Client_Hooks_PostRevpropChangeTest::main() if this source file is executed directly.
if (!defined("PHPUnit_MAIN_METHOD")) {
    define("PHPUnit_MAIN_METHOD", "USVN_Client_Hooks_PostRevpropChangeTest::main");
}

require_once "PHPUnit/Framework/TestCase.php";
require_once "PHPUnit/Framework/TestSuite.php";

require_once 'www/USVN/autoload.php';

/**
 * Test class for USVN_Client_Hooks_PostRevpropChange.
 * Generated by PHPUnit_Util_Skeleton on 2007-03-10 at 18:51:59.
 */
class USVN_Client_Hooks_PostRevpropChangeTest extends USVN_Client_Hooks_HookTest {
    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main() {
        require_once "PHPUnit/TextUI/TestRunner.php";

        $suite  = new PHPUnit_Framework_TestSuite("USVN_Client_Hooks_PostRevpropChangeTest");
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

   public function setUp()
    {
        parent::setUp();
        $this->hook = new USVN_Client_Hooks_PostRevpropChange('tests/tmp/testrepository', 1, "test", "svn:log", "M", "message de log");
		$this->setHttp();
    }

    public function test_postRevpropChange()
    {
		$this->hook->send();
        $request  = $this->hook->getLastRequest();
        $this->assertEquals('usvn.client.hooks.postRevpropChange', $request->getMethod());
        $this->assertSame(array('007', 1, "test", "svn:log", "M", "message de log"), $request->getParams());
    }
}

// Call USVN_Client_Hooks_PostRevpropChangeTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == "USVN_Client_Hooks_PostRevpropChangeTest::main") {
    USVN_Client_Hooks_PostRevpropChangeTest::main();
}
?>
