<?php
/**
 * Start commit  hook use by subversion hook
 *
 * @author Team USVN <contact@usvn.info>
 * @link http://www.usvn.info
 * @license http://www.cecill.info/licences/Licence_CeCILL_V2-en.txt CeCILL V2
 * @copyright Copyright 2007, Team USVN
 * @since 0.5
 * @package client
 * @subpackage hook
 *
 * This software has been written at EPITECH <http://www.epitech.net>
 * EPITECH, European Institute of Technology, Paris - FRANCE -
 * This project has been realised as part of
 * end of studies project.
 *
 * $Id$
 */

// Call USVN_Client_Hooks_StartCommitTest::main() if this source file is executed directly.
if (!defined("PHPUnit_MAIN_METHOD")) {
    define("PHPUnit_MAIN_METHOD", "USVN_Client_Hooks_StartCommitTest::main");
}

require_once "PHPUnit/Framework/TestCase.php";
require_once "PHPUnit/Framework/TestSuite.php";

require_once 'www/USVN/autoload.php';

/**
 * Test class for USVN_Client_Hooks_StartCommit.
 * Generated by PHPUnit_Util_Skeleton on 2007-03-10 at 19:09:03.
 */
class USVN_Client_Hooks_StartCommitTest extends USVN_Client_Hooks_HookTest {
    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main() {
        require_once "PHPUnit/TextUI/TestRunner.php";

        $suite  = new PHPUnit_Framework_TestSuite("USVN_Client_Hooks_StartCommitTest");
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    public function setUp()
    {
        parent::setUp();
        $this->hook = new USVN_Client_Hooks_StartCommit('tests/tmp/testrepository', 'toto');
		$this->setHttp();
    }

    public function test_startCommit()
    {
        $this->setServerResponseTo(0);
        $this->assertEquals(0, $this->hook->send());
        $this->setServerResponseTo("Start commit error");
        $this->assertEquals("Start commit error", $this->hook->send());
        $request  = $this->hook->getLastRequest();
        $this->assertSame('usvn.client.hooks.startCommit', $request->getMethod());
        $this->assertSame(array('007', 'toto'), $request->getParams());
    }
}

// Call USVN_Client_Hooks_StartCommitTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == "USVN_Client_Hooks_StartCommitTest::main") {
    USVN_Client_Hooks_StartCommitTest::main();
}
?>
