<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
	"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html>
	<head>
		<meta http-equiv="Content-type" content="text/html; charset=utf-8">
		<title>USVN</title>
		<? // $this->stylesheetTag('screen.css'); ?>
		<? // $this->faviconTag(''); ?>
		<link type="text/css" rel="stylesheet" media="screen" href="<?= $this->url(array('type' => 'stylesheets', 'name' => 'new.css'), 'medias')?>" />
		<link rel="shortcut icon" href="<?= $this->url(array('type' => 'images', 'name' => 'logo_small.tiff'), 'medias') ?>" />
	</head>
	<body>
		<div id="header">
		  <div id="shaddow">
	  	  <div id="header-wrapper">
	    	  <div id="logo">
	    		  &nbsp;
	    		</div>
	    		<div id="main-menu">
		          <ul>
		<? foreach (array('index', 'profile', 'admin', 'logout') as $menuLink): ?>
		            <li><a href="<?= $this->url(array('controller' => $menuLink), 'default') ?>" <?= ($menuLink == $this->controller ? ' id="selected"' : '') ?>><span><?= $menuLink ?></span></a></li>
		<? endforeach ?>
		          </ul>
	    		</div>
	  		</div>
			</div>
	  </div>
		<div id="container">
		  <div id="container-wrapper">
	  	  <div id="sub-menu">
		<? if (file_exists(USVN_VIEWS_DIR . '/' . $this->controller . '/' . '_submenu.phtml')): ?>
			<?= $this->partial('_submenu.phtml') ?>
		<? endif ?>
	  		</div>
	  		<div id="main">
				<?= $this->layout()->content ?>
	  		</div>
	  		<div id="hspacer">
	  		  &nbsp;
	  		</div>
	  		<div id="footer">
	  		  Footer
	<? //htmlspecialchars($this->headStyle('toto'), array('href' => '/toto')) ?>
	<? //htmlspecialchars($this->headLink(array('href' => '/toto'))) ?>
	<? //$this->headLink()->appendStylesheet('/toto') ?>
	<? //htmlspecialchars($this->headLink()) ?>
	<? // htmlspecialchars($this->url()) ?>
	<?// $this->mediaStylesheet?>
			<? // join(array_keys((array)$this), '<br />') ?>
	  		</div>
			</div>
		</div>
	</body>
</html>
