<form id="group" class="usvn_form" method="post" action="<?php echo $this->url ?>">
	<div>
	  <?php echo '', $this->formHidden('prefix', $this->prefix); ?>
		<label><?php echo T_("Name"); ?><span class="usvn_require">*</span>:<br />
			<?php
			  if ($this->prefix) {
			    echo $this->prefix, ' ', $this->formText('groups_name', $this->group->name, array('maxlength' => 255, 'size' => '77'));
			  } else {
			    echo '', $this->formText('groups_name', $this->group->name, array('maxlength' => 255, 'size' => '77'));
			  }
			?>
		</label>
		<br />
		<label><?php echo T_("Description"); ?>:<br />
			<?php echo $this->formTextarea('groups_description', $this->group->description, array('rows' => 8, 'cols' => 35)); ?>
		</label>
		<br/>
		<?php
			if ($this->action != "new" && !$this->error($this))
				echo '<a href="' . $this->url(array('controller' => 'group', 'group' => $this->group->name), 'group') . '">'. T_("Managing group")." ".$this->group->name . '</a>';
		?>
		<br />
		<?php echo $this->formSubmit('submit', T_("Submit"), array("onclick" => 'return checkName();')); ?>
	</div>
</form>
