<div class="usvn_info">
	<h1><?= T_("Groups") ?> <?= ($this->prefix != null ? '('.$this->prefix.')' : '') ?></h1>
</div>

<?php echo $this->error($this); ?>

<table class="sortable" id="grps">
	<thead>
		<tr>
			<th><?= T_('Name') ?></th>
			<th><?= T_('Description') ?></th>
			<th class="sorttable_nosort" width="56px"><?= T_('Action') ?></th>
		</tr>
	</thead>
	<tbody>

    <? $deletetext = T_("Do you really want to delete group %s?"); ?>
  	<?php if ($this->prefix): ?>
  	  <tr>
        <td><a href="<?= $this->url(array('action' => 'index', 'folder' => $this->prev)); ?>">
          <span class="grid_img">
  					<?= $this->img('folder.png') ?>
  				</span>
          ..
        </a></td><td>&nbsp;</td><td>&nbsp;</td>
      </tr>
  	<?php endif ?>
  	<? if (!empty($this->groups)): ?>
  	<? foreach ($this->groups as $group => $datas): ?>
	    <?php if ($datas instanceof USVN_Db_Table_Row_Project): ?>
  	    <tr>
          <td><a href="<?= $this->url(array('action' => 'index', 'folder' => $this->prefix.$group)); ?>">
            <span class="grid_img">
    					<?= $this->img('folder.png') ?>
    				</span>
            <?= $group ?>
          </a></td>
          <td><a href="<?= $editurl ?>"><?= nl2br($this->escape($datas->description)) ?></a></td>
          <td>&nbsp;</td>
        </tr>
      <?php else: ?>
        <? $editurl = $this->url(array('controller' => 'group', 'action' => 'edit', 'name' => $this->prefix.$group), 'admin', true); ?>
        <tr>
          <td><a href="<?= $this->url(array('action' => null, 'group' => $this->prefix.$group), 'group', true) ?>">
            <span class="grid_img">
    					<?= $this->img('group32.png') ?>
    				</span>
            <?= $group ?>
          </a></td>
          <td><a href="<?= $editurl ?>"><?= nl2br($this->escape($datas->description)) ?></a></td>
          <td class="align-right">
            <?= $this->editLink('group', 'name', $this->prefix.$group) ?>
            <?= $this->deleteLink('group', 'name', $this->prefix.$group, $deletetext) ?>
          </td>
        </tr>
      <?php endif ?>
  	<? endforeach ?>
  	<? endif ?>
  </tbody>
	<tfoot>
		<tr>
			<td colspan="3" class="align-right">
				<a href="<?= $this->url(array('action' => 'new')) ?>"><?= T_("Add new group") ?></a>
				<?= $this->addLink() ?>
			</td>
		</tr>
	</tfoot>
</table>
<br />

