<a href="<?php echo $this->url(array('controller' => 'config')); ?>"><?= T_("Configuration") ?></a>
<a href="<?php echo $this->url(array('controller' => 'group')); ?>"><?= T_("Groups") ?></a>
<a href="<?php echo $this->url(array('controller' => 'project')); ?>"><?= T_("Projects") ?></a>
<a href="<?php echo $this->url(array('controller' => 'systemreport')); ?>"><?= T_("System report") ?></a>
<a href="<?php echo $this->url(array('controller' => 'user')); ?>"><?= T_("Users") ?></a>