<?php
/**
 * Class to test group's model
 *
 * @author Team USVN <contact@usvn.info>
 * @link http://www.usvn.info
 * @license http://www.cecill.info/licences/Licence_CeCILL_V2-en.txt CeCILL V2
 * @copyright Copyright 2007, Team USVN
 * @since 0.5
 * @package Db
 * @subpackage Table
 *
 * This software has been written at EPITECH <http://www.epitech.net>
 * EPITECH, European Institute of Technology, Paris - FRANCE -
 * This project has been realised as part of
 * end of studies project.
 *
 * $Id$
 */

// Call USVN_Auth_Adapter_DbTest::main() if this source file is executed directly.
if (!defined("PHPUnit_MAIN_METHOD")) {
    define("PHPUnit_MAIN_METHOD", "USVN_Db_Table_GroupsTest::main");
}

require_once "PHPUnit/Framework/TestCase.php";
require_once "PHPUnit/Framework/TestSuite.php";

require_once 'www/USVN/autoload.php';
define('CONFIG_FILE', 'tests/config.ini');

/**
 * Test class for USVN_Auth_Adapter_Db.
 * Generated by PHPUnit_Util_Skeleton on 2007-03-25 at 09:51:30.
 */
class USVN_Db_Table_GroupsTest extends USVN_Test_DB {

    public static function main() {
        require_once "PHPUnit/TextUI/TestRunner.php";

        $suite  = new PHPUnit_Framework_TestSuite("USVN_Db_Table_GroupsTest");
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    public function testInsertGroupNoName()
	{
		$table = new USVN_Db_Table_Groups();
		$obj = $table->fetchNew();
		$obj->setFromArray(array('groups_name' => ''));
		try {
			$id = $obj->save();
		}
		catch (USVN_Exception $e) {
			$this->assertContains("group's name is empty", $e->getMessage());
			return;
		}
		$this->fail();
    }

    public function testInsertGroupNoName2()
	{
		$table = new USVN_Db_Table_Groups();
		$obj = $table->fetchNew();
		$obj->setFromArray(array('groups_name' => "   \t    "));
		try {
			$id = $obj->save();
		}
		catch (USVN_Exception $e) {
			$this->assertContains("group's name is empty", $e->getMessage());
			return;
		}
		$this->fail();
    }

    public function testInsertGroupInvalidName()
	{
		$table = new USVN_Db_Table_Groups();
		$obj = $table->fetchNew();
		$obj->setFromArray(array('groups_name' => "   !!!    "));
		try {
			$id = $obj->save();
		}
		catch (USVN_Exception $e) {
			$this->assertContains("group's name is invalid", $e->getMessage());
			return;
		}
		$this->fail();
	}

    public function testInsertGroupOk()
	{
		$table = new USVN_Db_Table_Groups();
		$obj = $table->fetchNew();
		$obj->setFromArray(array('groups_name' => 'InsertGroupOk'));
		$obj->save();
		$this->assertTrue($table->isAGroup('InsertGroupOk'));
    }

    public function testUpdateGroupNoName()
	{
		$table = new USVN_Db_Table_Groups();
		$obj = $table->fetchNew();
		$obj->setFromArray(array('groups_name' => 'UpdateGroupNoName'));
		$id = $obj->save();
		$obj = $table->find($id)->current();
		$obj->setFromArray(array('groups_name' => ''));
		try {
			$id = $obj->save();
		}
		catch (USVN_Exception $e) {
			$this->assertContains("group's name is empty", $e->getMessage());
			return;
		}
		$this->fail();
	}

    public function testUpdateGroupOk()
	{
		$table = new USVN_Db_Table_Groups();
		$obj = $table->fetchNew();
		$obj->setFromArray(array('groups_name' => 'UpdateGroupOk'));
		$id = $obj->save();
		$this->assertTrue($table->isAGroup('UpdateGroupOk'));
		$obj = $table->find($id)->current();
		$obj->setFromArray(array('groups_name' => 'UpdateGroupOk2'));
		$id = $obj->save();
		$this->assertTrue($table->isAGroup('UpdateGroupOk2'));
    }

    public function testUpdateOnlyDesc()
	{
		$table = new USVN_Db_Table_Groups();
		$obj = $table->fetchNew();
		$obj->setFromArray(array('groups_name' => 'UpdateGroupOk'));
		$id = $obj->save();
		$this->assertTrue($table->isAGroup('UpdateGroupOk'));
		$obj = $table->find($id)->current();
		$obj->setFromArray(array('groups_description' => 'test'));
		$id = $obj->save();
		$this->assertTrue($table->isAGroup('UpdateGroupOk'));
    }

	public function testFindUserInGroup()
	{
		$user = new USVN_Db_Table_Users();
		$user->insert(
			array(
				"users_id" => 2,
				"users_login" => "test",
				"users_password" => USVN_Crypt::crypt("test")
			)
		);
		$user->insert(
			array(
				"users_id" => 3,
				"users_login" => "babar",
				"users_password" => USVN_Crypt::crypt("test")
			)
		);
		$user->insert(
			array(
				"users_id" => 4,
				"users_login" => "john",
				"users_password" => USVN_Crypt::crypt("test")
			)
		);

		$group_table = new USVN_Db_Table_Groups();
		$group_table->insert(array("groups_id" => 2, "groups_name" => "toto"));

		$user_groups = new USVN_Db_Table_UsersToGroups();
		$user_groups->insert(
			array(
				"groups_id" => 2,
				"users_id" => 2
			)
		);
		$user_groups->insert(
			array(
				"groups_id" => 2,
				"users_id" => 3
			)
		);
		$group = $group_table->find(2)->current();
		$users = $group->findManyToManyRowset('USVN_Db_Table_Users', 'USVN_Db_Table_UsersToGroups');
		$res = array();
		foreach ($users as $user) {
			array_push($res, $user->users_login);
		}
		$this->assertContains("test", $res);
		$this->assertContains("babar", $res);
		$this->assertNotContains("john", $res);
	}
}

// Call USVN_Auth_Adapter_DbTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == "USVN_Db_Table_GroupsTest::main") {
    USVN_Db_Table_GroupsTest::main();
}
?>
