<div class="usvn_info">
	<h1><?php echo T_("Homepage"); ?></h1>
</div>
<div id="usvn_list_project">
	<h3><?php echo T_("Your projects") . ":"; ?></h3>
<?php
if (count($this->projects)) {
	echo '<ul>';
	foreach ($this->projects as $project) {
		echo '<li><a href="' . $this->url(array('project' => $project->name), 'project') . '">' . $project->name . '</a></li>';
	}
	echo '</ul>';
}
else {
	echo "<p>" . T_("You don't have any project.") . "</p>";
}
?>
</div>
