#!/usr/bin/env php
<?php
set_include_path(get_include_path().PATH_SEPARATOR .dirname(__FILE__).'/../usvn');

require_once('USVN/Client/Hooks/PostRevpropChange.php');
require_once('USVN/Client/ConsoleUtils.php');

try
{
	$propertyvalue = rtrim(stream_get_contents(STDIN), "\n");
    $hook = new USVN_Client_Hooks_PostRevpropChange($argv[1], $argv[2], $argv[3], $argv[4], $argv[5], $propertyvalue);
	$res = $hook->send();
	if ($res) {
		USVN_Client_ConsoleUtils::writeOnStdError($res."\n");
		exit(1);
	}
	exit(0);
}
catch (Exception $e)
{
	USVN_Client_ConsoleUtils::writeOnStdError($e->getMessage()."\n");
    exit(1);
}