#!/usr/bin/env php
<?php
set_include_path(get_include_path().PATH_SEPARATOR .dirname(__FILE__).'/../usvn');

require_once('USVN/Client/Hooks/PostCommit.php');
require_once('USVN/Client/ConsoleUtils.php');

try
{
    $hook = new USVN_Client_Hooks_PostCommit($argv[1], $argv[2]);
	$hook->send();
	exit(0);
}
catch (Exception $e)
{
	USVN_Client_ConsoleUtils::writeOnStdError($e->getMessage()."\n");
    exit(1);
}