#!/usr/bin/env php
<?php
set_include_path(get_include_path().PATH_SEPARATOR .dirname(__FILE__).'../usvn');

require_once('USVN/Client/Hooks/StartCommit.php');

try
{
    $hook = new USVN_Client_Hooks_StartCommit($args[1], $args[2]);
    exit($hook->send());
}
catch (Exception $e)
{
    echo $e->getMessage()."\n";
    exit(1);
}