<?php echo $this->error($this); ?>
<script type="text/javascript">
<!--
function checkName() {
	var spanError = document.getElementById('error');
	var checkRegExp = new RegExp("^[ \t]*$");
	var project = document.getElementById('project');
	if (project.projects_name.value.length == 0
	|| checkRegExp.test(project.projects_name.value)) {
		spanError.innerHTML = "<?php echo T_('Project\'s name empty, please fill it.'); ?>;"
		spanError.className = "usvn_error";
		return false;
	}
	spanError.innerHTML = '';
	spanError.className = "";
	return true;
}
-->
</script>
<form id="project" class="usvn_form" method="post" action="<?php echo $this->url; ?>">
	<fieldset>
		<legend><?php echo T_("Project's information"); ?></legend>

			<label><?php echo T_("Name"); ?><span class="usvn_require">*</span>:<br />
			<?php echo $this->formText('projects_name', $this->project->name, array('maxlength' => 255)); ?>
		</label>
		<br />
		<label><?php echo T_("Description"); ?>:<br />
			<?php echo $this->formTextarea('projects_description',$this->project->description, array('rows' => 8, 'cols' => 80)); ?>
		</label>
		<br />
        <?php
        if ($this->action == 'new' || $this->action == 'create') {
        	echo '<table>';
        	echo '<tr><td><label for="creategroup">' . T_('Create group for project:') . '</label></td><td>'. $this->formCheckbox('creategroup', 1) . '</td></tr>';
        	echo '<tr><td><label for="addmetogroup">' . T_('Add me to project group:') . '</label></td><td>'. $this->formCheckbox('addmetogroup', 1) . '</td></tr>';
        	echo '<tr><td><label for="admin">' . T_('Add me as admin of the project:') . '</label></td><td>'. $this->formCheckbox('admin', 1) . '</td></tr>';
        	echo '<tr><td><label for="createsvndir">' . T_('Create SVN standard directories (/trunk, /branches and /tags):') . '</label></td><td>'. $this->formCheckbox('createsvndir', 1) . '</td></tr>';
        	echo '</table>';
        } else if ($this->action == 'edit') {
        	if ($this->AdminProject != 1) {
        		echo '<label>' . T_('Add me as admin of the project:') . '<input type = "checkbox" name="admin" value="admin"></label>';
        	} else {
        		echo '<label>' . T_('Add me as admin of the project:') . '<input type = "checkbox" name="admin" value="admin" checked ></label>';
        	}
        }
        ?>
		<?php if (isset($this->group)) echo $this->formHidden('groups_id', $this->group->id); ?>
		<br />
	</fieldset>
	<?php if (is_object($this->project_notification)) { ?>
	<fieldset>
		<legend><?php echo T_("Post-commit email notification settings"); ?></legend>
                <?php
        	if ($this->project_notification->enabled) {
        		echo '<label>' . T_('Send notification after each commit:') . '<input type = "checkbox" name="notification" value="notification" checked ></label>';
        	} else {
        		echo '<label>' . T_('Send notification after each commit:') . '<input type = "checkbox" name="notification" value="notification"></label>';
        	}
                ?>
		<br />
			<label><?php echo T_("Subject"); ?>:<br />
			<?php echo $this->formText('notify_subject', $this->project_notification->getSubject(), array('maxlength' => 255)); ?>
		</label>
		<br />
		<label><?php echo T_("Message"); ?>:<br />
			<?php echo $this->formTextarea('notify_text',$this->project_notification->getText(), array('rows' => 8, 'cols' => 80)); ?>
		</label>
		<br />
		<label><?php echo T_("Recipients"); ?>:<br />
			<?php echo $this->formTextarea('notify_recipients',implode("\n", $this->project_notification->getRecipients()), array('rows' => 8, 'cols' => 80)); ?>
		</label>
		<br />
	</fieldset>
	<? } ?>
		<?php echo $this->formSubmit('submit', T_("Submit"), array("onclick" => 'return checkName();')); ?>
</form>
<br />
