<script type="text/javascript">
HTMLTableToolsOptions.multiColSort = false;
HTMLTableToolsOptions.showSortIndex = false;
HTMLTableToolsOptions.skipCells = [3];
</script>
<div class="usvn_info_project">
	<h1><?php echo T_("Projects"); ?></h1>
</div>
<?php

print '<table class="sortable" id="projects">' .
		'<thead><tr>' .
		'<th>' . T_('Name') . '</th>' .
		'<th>' . T_('Description') . '</th>' .
		'<th>' . T_('Action') . '</th>' .
		'</tr></thead><tbody>';

if (count($this->projects)) {
	foreach ($this->projects as $project) {
		$editurl = $this->url(array('action' => 'edit', 'name' => $project->name));
		$deletetext = T_("Do you really want to delete project %s?");
		echo <<<EOF
		<tr>
			<td><a href="{$editurl}">{$project->projects_name}</a></td>
			<td><a href="{$editurl}">{$project->projects_description}</a></td>
			<td>
				{$this->homeLink($project->name)}
				{$this->editLink('name', $project->name)}
                {$this->deleteLink('name', $project->name, $deletetext)}
                {$this->ACLLink($project->name)}
            </td>
		</tr>
EOF;
	}
}
print '</tbody></table><br />';

