<?php
/**
 * Uninstall usvn hooks.
 *
 * @author Team USVN <contact@usvn.info>
 * @link http://www.usvn.info
 * @license http://www.cecill.info/licences/Licence_CeCILL_V2-en.txt CeCILL V2
 * @copyright Copyright 2007, Team USVN
 * @since 0.5
 * @package client
 * @subpackage uninstall
 *
 * This software has been written at EPITECH <http://www.epitech.net>
 * EPITECH, European Institute of Technology, Paris - FRANCE -
 * This project has been realised as part of
 * end of studies project.
 *
 * $Id$
 */

// Call USVN_Client_UninstallTest::main() if this source file is executed directly.
if (!defined("PHPUnit_MAIN_METHOD")) {
    define("PHPUnit_MAIN_METHOD", "USVN_Client_UninstallTest::main");
}

require_once "PHPUnit/Framework/TestCase.php";
require_once "PHPUnit/Framework/TestSuite.php";

require_once 'www/USVN/autoload.php';

/**
 * Test class for USVN_Client_Uninstall.
 * Generated by PHPUnit_Util_Skeleton on 2007-03-10 at 18:25:06.
 */
class USVN_Client_UninstallTest extends USVN_Client_CommandTest {
    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main() {
        require_once "PHPUnit/TextUI/TestRunner.php";

        $suite  = new PHPUnit_Framework_TestSuite("USVN_Client_UninstallTest");
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    public function test_notSvnRepository()
    {
        try {
            new USVN_Client_Uninstall('tests/tmp/fakerepository');
        }
        catch (Exception $e) {
            return;
        }
        $this->fail();
    }

    public function test_uninstallHook()
    {
        $install = new USVN_Client_Install('tests/tmp/testrepository', 'http://example.com', 'project-love', 'auth007', $this->httpClient);
        $unistall = new USVN_Client_Uninstall('tests/tmp/testrepository');
        $this->assertFalse(file_exists('tests/tmp/testrepository/hooks/start-commit'));
        $this->assertFalse(file_exists('tests/tmp/testrepository/usvn'));
    }
}

// Call USVN_Client_UninstallTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == "USVN_Client_UninstallTest::main") {
    USVN_Client_UninstallTest::main();
}
?>
