<div class="usvn_info">
	<h1><?php echo T_("System report");?></h1>
</div>

<table>
	<tr><td><?php echo T_("PHP version:");?></td><td><?php echo phpversion();?></td></tr>
	<tr><td><?php echo T_("USVN version:");?></td><td><?php echo $this->config->version;?></td></tr>
	<tr><td><?php echo T_("Translation:");?></td><td><?php echo $this->config->translation->locale;?></td></tr>
	<tr><td><?php echo T_("Database:");?></td><td><?php echo $this->config->database->adapterName;?></td></tr>
	<tr><td><?php echo T_("Subversion version:");?></td><td><?php echo $this->subversionversion;?></td></tr>
	<tr><td><?php echo T_("OS:");?></td><td><?php echo PHP_OS;?></td></tr>
</table>

<br />
<a href="<?php echo $this->config->url->base . '/admin/systemreportxml';?>"><?php echo T_("Get full report"); ?></a>
<br /><br /><br />

<div class="usvn_subinfo">
	<h2><?php echo T_("PHP extensions")?></h2>
</div>

<ul>
	<?php foreach (get_loaded_extensions() as $ext) { ?>
		<li><?php echo $ext; ?></li>
		<?php } ?>
</ul>

<br /><br />
<?php if (function_exists("apache_get_modules")) { ?>
	<div class="usvn_subinfo">
		<h2><?php echo T_("Apache modules")?></h2>
	</div>
	<ul>
	<?php foreach (apache_get_modules() as $ext) { ?>
		<li><?php echo $ext; ?></li>
	<?php } ?>
	</ul>
<?php }  ?>