<?php echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>"; ?>
<rss version="2.0">
<channel>
<title>
<?php echo "Project : " . $this->project->projects_name ?>
</title>
<?php
if ($this->project->projects_description)
	echo "<description>".$this->project->projects_description."</description>";
?>
<?php
foreach (array_keys($this->log) as $revision)
{
	$commit = $this->log[$revision];
	echo "<item>";
	echo "<title>" . $this->project->projects_name . " " . T_("revision") . " " . $revision . "</title>";
	echo "<guid isPermaLink='true'>myguid".$revision."</guid>";
	echo "<description><![CDATA[".T_("Revision")." : {$revision}<br />".T_("Author")." : {$commit['author']}<br />".T_("Date")." : ";
	echo date("Y-m-d",  $commit["date"])." ". date("H:i", $commit["date"])."<br />".T_("Message")." : ".nl2br($commit['msg'])."<br />]]></description>";
	echo "</item>";
}
?>
</channel>
</rss>
