<?php
// Call USVN_ConfigTest::main() if this source file is executed directly.
if (!defined("PHPUnit_MAIN_METHOD")) {
    define("PHPUnit_MAIN_METHOD", "USVN_ConfigTest::main");
}

require_once "PHPUnit/Framework/TestCase.php";
require_once "PHPUnit/Framework/TestSuite.php";

require_once 'www/USVN/autoload.php';

/**
 * Test class for USVN_Config.
 * Generated by PHPUnit_Util_Skeleton on 2007-03-21 at 16:49:21.
 */
class USVN_ConfigTest extends PHPUnit_Framework_TestCase {
	private $config;

    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main() {
        require_once "PHPUnit/TextUI/TestRunner.php";

        $suite  = new PHPUnit_Framework_TestSuite("USVN_ConfigTest");
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    protected function setUp() {
		file_put_contents("tests/tmp/test.ini",'[global]
test1 = "Test 1"
test2.value = "Test 2"
test2.key = "Test key 2"
test3.subvalue.value = "Test 3"
test4 = "Test 4"
		');
		$this->config = new USVN_Config("tests/tmp/test.ini", "global");
    }

    protected function tearDown() {
		unlink("tests/tmp/test.ini");
    }

    public function testSaveNoChange() {
		$this->test1 = "Test 1 Modif";
		$this->config->save();
		$config2 = new Zend_Config_Ini("tests/tmp/test.ini", "global");
		$this->assertEquals("Test 1", $config2->test1);
		$this->assertEquals("Test 2", $config2->test2->value);
		$this->assertEquals("Test key 2", $config2->test2->key);
		$this->assertEquals("Test 3", $config2->test3->subvalue->value);
		$this->assertEquals("Test 4", $config2->test4);
    }

    public function testSave() {
		$this->config->test1 = "Test 1 Modif";
		$this->assertEquals("Test 1 Modif", $this->config->test1);
		$this->config->save();
		$config2 = new Zend_Config_Ini("tests/tmp/test.ini", "global");
		$this->assertEquals("Test 1 Modif", $config2->test1);
		$this->assertEquals("Test 1 Modif", $config2->test1);
    }

}

// Call USVN_ConfigTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == "USVN_ConfigTest::main") {
    USVN_ConfigTest::main();
}
?>
