<?php
/**
 * Import users from an htpasswd file to USVN
 *
 * @author Team USVN <contact@usvn.info>
 * @link http://www.usvn.info
 * @license http://www.cecill.info/licences/Licence_CeCILL_V2-en.txt CeCILL V2
 * @copyright Copyright 2007, Team USVN
 * @since 0.7
 * @package admin
 *
 * This software has been written at EPITECH <http://www.epitech.net>
 * EPITECH, European Institute of Technology, Paris - FRANCE -
 * This project has been realised as part of
 * end of studies project.
 *
 * $Id: ImportHtpasswdTest.php 1188 2007-10-06 12:03:17Z dolean_j $
 */

// Call USVN_ImportHtpasswdTest::main() if this source file is executed directly.
if (!defined("PHPUnit_MAIN_METHOD")) {
    define("PHPUnit_MAIN_METHOD", "USVN_ImportSVNRepositoriesTest::main");
}

require_once "PHPUnit/Framework/TestCase.php";
require_once "PHPUnit/Framework/TestSuite.php";

define('CONFIG_FILE', 'tests/config.ini');
require_once 'www/USVN/autoload.php';

/**
 * Test class for USVN_ImportHtpasswd.
 * Generated by PHPUnit_Util_Skeleton on 2007-04-03 at 09:22:11.
 */
class USVN_ImportRepositoriesTest extends USVN_Test_DB {
    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main() {
        require_once "PHPUnit/TextUI/TestRunner.php";

        $suite  = new PHPUnit_Framework_TestSuite("USVN_ImportSVNRepositoriesTest");
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

	public function tearDown() {
		parent::tearDown();
	}

	public function testOne()
	{
	}

}

// Call USVN_ImportHtpasswdTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == "USVN_ImportSVNRepositoriesTest::main") {
    USVN_ImportRepositoriesTest::main();
}
?>
