<?php
/**
* @package usvn
* @subpackage utils
*
*/

// Call USVN_TranslationTest::main() if this source file is executed directly.
if (!defined("PHPUnit_MAIN_METHOD")) {
    define("PHPUnit_MAIN_METHOD", "USVN_TranslationTest::main");
}

require_once "PHPUnit/Framework/TestCase.php";
require_once "PHPUnit/Framework/TestSuite.php";

require_once 'www/USVN/autoload.php';

/**
 * Test class for USVN_Translation.
 * Generated by PHPUnit_Util_Skeleton on 2007-03-10 at 16:05:57.
 */
class USVN_TranslationTest extends PHPUnit_Framework_TestCase {
    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main() {
        require_once "PHPUnit/TextUI/TestRunner.php";

        $suite  = new PHPUnit_Framework_TestSuite("USVN_TranslationTest");
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, close a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown() {
    }

    public function test_getLanguage()
    {
		USVN_Translation::initTranslation('fr_FR');
		$this->assertEquals('fr_FR', USVN_Translation::getLanguage());
	}

    public function test_getLocaleDirectory()
    {
		USVN_Translation::initTranslation('fr_FR', 'tests');
		$this->assertEquals('tests', USVN_Translation::getLocaleDirectory());
	}

	public function test_translation()
    {
		USVN_Translation::initTranslation('fr_FR');
		$this->assertEquals("Bienvenue dans USVN", T_("Welcome to USVN"), "Translation error.");
	}
}

// Call USVN_TranslationTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == "USVN_TranslationTest::main") {
    USVN_TranslationTest::main();
}
?>
