<div class="usvn_info_config">
	<h1><?php echo T_("Configuration"); ?></h1>
</div>
<form class="usvn_form" method="post" action="<?php echo $this->url(array('action' => 'save'));?>">
<fieldset>
	<legend><?php echo T_("General settings");?></legend>
	<table>
		<tr>
			<td><label><?php echo T_("Default language");?>:</label></td>
			<td>
				<select name="language">
					<?php
						foreach (USVN_Translation::listTranslation() as $language) {
                            $locale = new Zend_Locale($language);
                            $lang_name = $this->locale->getLanguageTranslation($locale->getLanguage());
							if ($language == USVN_Translation::getLanguage()) {
								echo "<option value=\"$language\" selected=\"selected\">$lang_name</option>";
							} else {
								echo "<option value=\"$language\">$lang_name</option>";
							}
						}
					?>
				</select>
			</td>
		</tr>
		<tr>
			<td><label><?php echo T_("Default timezone");?>:</label></td>
			<td>
				<select name="timezone">
					<?php
						$timezones = Zend_Locale_Data::getContent("en", "timezonestandard");
						ksort($timezones);
						foreach ($timezones as $timezone => $city) {
							if ($timezone == date_default_timezone_get()) {
								echo "<option selected=\"selected\">$timezone</option>";
							} else {
								echo "<option>$timezone</option>";
							}
						}
					?>
				</select>
			</td>
		</tr>
		<tr>
			<td><label><?php echo T_("Default template");?>:</label></td>
			<td>
				<select name="template">
					<?php
						foreach (USVN_Template::listTemplate() as $template) {
							if ($template == USVN_Template::getTemplate()) {
								echo "<option selected=\"selected\">$template</option>";
							} else {
								echo "<option>$template</option>";
							}
						}
					?>
				</select>
			</td>
		</tr>
	</table>
</fieldset>
<fieldset>
	<legend><?php echo T_("Site's information");?></legend>
	<table>
		<tr>
			<td><label><?php echo T_("Title"); ?>:</label></td>
			<td>
				<?php echo $this->formText('siteTitle', $this->config->site->title, array('size' => 80)); ?>
			</td>
		</tr>
		<tr>
			<td><label><?php echo T_("Icone"); ?>:</label></td>
			<td>
				<?php echo $this->formText('siteIco', $this->config->site->ico, array('size' => 80)); ?>
			</td>
		</tr>
		<tr>
			<td><label><?php echo T_("Logo"); ?>:</label></td>
			<td>
				<?php echo $this->formText('siteLogo', $this->config->site->logo, array('size' => 80)); ?>
			</td>
		</tr>
	</table>
</fieldset>
<p>
	<input type="submit" value="<?php echo T_("Save");?>" />
</p>
</form>
